#!/usr/bin/env bash
# Launches the Kyty Launcher (Tauri UI).
#
# Default: builds the release binary if needed and runs it standalone, the
# same binary the .desktop entry launches (see scripts/install-desktop-entry.sh
# for why debug and release are not interchangeable: the debug binary has
# devUrl http://localhost:1421 baked in and fails standalone with "Could not
# connect to localhost: Connection refused").
#
# ./start.sh              build if needed, then run the release binary
# ./start.sh --dev        npm run tauri dev (Vite HMR on :1421 + debug binary)
# ./start.sh --no-build   run the existing release binary, skip the build step
# ./start.sh -- <args>    everything after -- is forwarded to the launcher binary
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

mode="release"
no_build=0
passthrough=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dev)
      mode="dev"
      shift
      ;;
    --no-build)
      no_build=1
      shift
      ;;
    --)
      shift
      passthrough=("$@")
      break
      ;;
    *)
      echo "unknown argument: $1" >&2
      echo "usage: $0 [--dev] [--no-build] [-- args-for-launcher]" >&2
      exit 1
      ;;
  esac
done

for tool in npm cargo; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "error: $tool not found on PATH, required to run the launcher." >&2
    exit 1
  fi
done

if [[ ! -d node_modules ]]; then
  echo "node_modules missing, running npm ci first"
  npm ci
fi

emulator_hint="../../_Build/linux/install/kyty_emulator"
if [[ ! -x "$emulator_hint" ]]; then
  echo "warning: no kyty_emulator found at $emulator_hint" >&2
  echo "         the launcher UI will still start, but pressing Launch will" >&2
  echo "         fail with \"Could not find kyty_emulator\" until the emulator is built." >&2
fi

if [[ "$mode" == "dev" ]]; then
  if command -v ss >/dev/null 2>&1; then
    holder="$(ss -ltnp 'sport = :1421' 2>/dev/null | awk 'NR>1')"
    if [[ -n "$holder" ]]; then
      echo "Port 1421 is already in use, so a second Vite dev server can't start." >&2
      echo "That means this run stops here instead of launching the UI; nothing else is affected." >&2
      echo "What is holding it:" >&2
      echo "  $holder" >&2
      echo "Stop it first, e.g.: kill \$(ss -ltnp 'sport = :1421' | awk 'NR>1 {print \$NF}' | grep -oP '(?<=pid=)\\d+')" >&2
      exit 1
    fi
  fi
  exec npm run tauri dev -- "${passthrough[@]}"
fi

bin="src-tauri/target/release/kyty-launcher"
target_dir="src-tauri/target"
build_root_marker="$target_dir/.build-root"
root="$(pwd)"

# Cargo caches build-script stdout (incl. absolute paths tauri_build bakes in,
# e.g. permission-file locations) keyed by a fingerprint that does not include
# the crate's absolute path. If src-tauri/target/ is ever copied or mirrored
# to a different absolute path (has happened via the greenboost mirror under
# greenboost-sources/), Cargo replays the stale cached paths instead of
# rerunning the build script, and the build fails with a "No such file or
# directory" on an autogenerated permissions file that exists fine locally,
# just under the wrong recorded path. Guard against that by recording which
# absolute path target/ was built under, and wiping it if that ever changes.
if [[ -d "$target_dir" ]]; then
  if [[ ! -f "$build_root_marker" || "$(cat "$build_root_marker" 2>/dev/null)" != "$root" ]]; then
    echo "note: $target_dir was built under a different path (or predates this check), cleaning it to avoid a stale build-script cache" >&2
    rm -rf "$target_dir"
  fi
fi

if [[ $no_build -eq 1 ]]; then
  if [[ ! -x "$bin" ]]; then
    echo "error: $bin does not exist and --no-build was passed." >&2
    echo "       build it first: npm run tauri build -- --no-bundle" >&2
    exit 1
  fi
else
  needs_build=1
  if [[ -x "$bin" ]]; then
    watch_paths=()
    for p in src src-tauri/src src-tauri/Cargo.toml src-tauri/Cargo.lock \
             src-tauri/tauri.conf.json src-tauri/capabilities src-tauri/build.rs \
             package.json package-lock.json vite.config.ts index.html; do
      [[ -e "$p" ]] && watch_paths+=("$p")
    done
    if [[ ${#watch_paths[@]} -gt 0 ]]; then
      newest="$(find "${watch_paths[@]}" -type f -newer "$bin" 2>/dev/null | head -n1)" || true
      [[ -z "$newest" ]] && needs_build=0
    fi
  fi

  if [[ $needs_build -eq 1 ]]; then
    npm run tauri build -- --no-bundle
    mkdir -p "$target_dir"
    echo "$root" > "$build_root_marker"
  else
    echo "nothing changed since the last build, skipping build and starting $bin directly"
  fi
fi

exec "$bin" "${passthrough[@]}"
